### PR TITLE
typo - not tokio but mio

### PR DESCRIPTION
**Pull request by dimbleby**

### CODE REVIEW

**Comment by dimbleby** [comment]
Ping!

Any views on my pull requests?  Understood that this repo is probably not a high priority - indeed I guess that's kinda the point.  Still, I hope that this and #4 are in the wholly-uncontroversial, obviously-just-merge class; and that even the slightly more complex #3 shouldn't detain you for long.

Thanks!

**Comment by dimbleby** [comment]
any comments?

**Comment by dimbleby** [comment]
Hi, 

I mean, I'm beginning to get the message, but... even if the answer is "I have no intention of doing anything with this repository" - would you mind explicitly saying so?

Especially as `mio 0.7` approaches in which, I think, the deprecated stuff is actually going to be removed: it would be good to know whether there's any chance of pull requests being accepted here.

Cheers!

**Comment by osa1** [comment]
@dimbleby see https://github.com/carllerche/mio-more/pull/2#issuecomment-333616345

**Comment by dimbleby** [comment]
OK, I give in!

I've published [mio-extras](https://crates.io/crates/mio-extras), which is this crate but tidied up in various ways:
* my three pull requests: #3, #4, and #5
* copied relevant test scripts across from the mio repository
* wrote basic docs, removed implementation details of the Channel from the public API
* clippy, rustfmt, travis

@carllerche: if you change your mind about ignoring this just let me know - I'd be happy to have just one crate with this stuff in it rather than two.

anyone else: I intend `mio-extras` to be a low maintenance crate from my point-of-view but by all means please chip in.

**Comment by carllerche** [comment]
@dimbleby I'd be happy to take a PR to mio replacing `mio-more` w/ `mio-extras`.

**Comment by dimbleby** [comment]
that's exactly what carllerche/mio#779 is, yes?

**Comment by carllerche** [comment]
Sorry, I'm still catching up from being away last month.

**Pull request closed without merging**
